server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

spring:
  config:
    activate:
      on-profile: eureka
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      hints:
        where-for-dinner-ui:
          hint: http
        where-for-dinner-search:
          hint: http
        where-for-dinner-availability:
          hint: http
        
    gateway:
      x-forwarded:
        enabled: true
        for-enabled: true
        proto-enabled: true
        host-append: false
        port-append: false
        proto-append: false
      routes:
        - id: ui-root-route
          uri: http://where-for-dinner-ui.apps.internal:8080
          order: 1000
          predicates:
            - Path=/**
            - Method=GET
          filters:
            - StripPrefix=0
          metadata:
            tags:
              - ui
        - id: ui-diningsearch-route
          uri: http://where-for-dinner-ui.apps.internal:8080
          predicates:
            - Path=/diningsearch/**
            - Method=GET
          filters:
            - StripPrefix=0
        - id: search-api-route
          uri: lb:http://where-for-dinner-search
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=0
            - RewritePath=/api/search(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Forwarded
          metadata:
            tags:
              - search-api
        - id: availability-api-route
          uri: lb:http://where-for-dinner-availability
          predicates:
            - Path=/api/availability/**
          filters:
            - StripPrefix=0
            - RewritePath=/api/availability(?<segment>/?.*), ${segment}
            - RemoveRequestHeader=Forwarded
          metadata:
            tags:
              - availability-api
    services:
      registrationMethod: direct
  cloud.refresh.refreshable: false

eureka:
  client:
    fetchRegistry: true

management:
  security:
    enabled: false
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
